#pragma config(Sensor, in1,    lightSensor,    sensorReflection)
#pragma config(Sensor, in2,    lineFollower,   sensorLineFollower)
#pragma config(Sensor, dgtl1,  bumpSwitch,     sensorTouch)
#pragma config(Motor,  port1,           flashlight,    tmotorVexFlashlight, openLoop, reversed)
#pragma config(Motor,  port2,           servo,         tmotorServoStandard, openLoop)
#pragma config(Motor,  port3,           openMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           sortMotor,     tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void open();
void openSort();

task main()
{

	//line threshold
	int lineThresh = 1800;

	//Light value Threshold
	int lightThresholdLow= 55;
	int lightThresholdHigh = 140;

	//Servo Positions
	int pos1 = -50;
	int pos2 = 50;
	int pos3 = 110;
	int pos4 = -110;

	turnFlashlightOn(flashlight, 150);

	while(true){

		bool isLight = false;
		bool isMedium = false;
		bool isWood = false;

		setServo(sortMotor, 25);
		setServo(servo, 0);

		open();

		wait(2);
		if(SensorValue(lineFollower) <= lineThresh){
			isWood = true;
		}
		if(SensorValue(lightSensor)<=lightThresholdLow){
			isLight = true;
		}
		else if(SensorValue(lightSensor)<=lightThresholdHigh){
			isMedium = true;
		}

		wait(2);

		if(isWood){
			setServo(servo, pos1);
		}
		else if(isLight){
			setServo(servo, pos2);
		}
		else if(isMedium){
			setServo(servo, pos3);
		}
		else{
			setServo(servo, pos4);
		}
		openSort();
	}

}

void open(){
	startMotor(openMotor, 15);
	wait(0.65);
	stopMotor(openMotor);
}

void openSort(){
	setServo(sortMotor, 25);
	wait(0.5);
	setServo(sortMotor, -127);
	wait(1);
	setServo(sortMotor, 25);
}
